services:
  - type: web
    name: cardgame-frontend
    env: static
    region: singapore
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: cardgame-backend
    env: node
    rootDir: backend
    region: singapore
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: cardgame-redis
          property: connectionString

  - type: redis
    name: cardgame-redis
    region: singapore
    ipAllowList: [] # Secure: Only allow internal traffic
    plan: free



